version: '3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: pass123
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
